 import React,{ v4 as uuidv4 } from    "uuid";
    export const option1 =  [
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        
    ]
    export const option2 =  [
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        
    ]
    export const option3 =  [
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        
    ]
    export const option4 =  [
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        { id: uuidv4(), craft: 'psn', checked: false, Default: false},
        
    ]
   